//create new user
POST  http://localhost:3002/users
Content-Type: application/json

{
    "name":"Jyothika",
    "age":21,
    "mobile_no":"9494344363",
    "email":"jyothika.e@westagilelabs.com",
    "password":"jyothika123"
}

//create new note

POST http://localhost:3002/notes
Content-Type: application/json

{
    "user_id":1,
    "note":"Our miniproject is started"
}