//login

POST http://localhost:3002/users/login
Content-Type: application/json
{
    "email":"jyothika@gmail.com",
    "password":"jyo123"
}



//new user
POST  http://localhost:3002/users/signup
Content-Type: application/json

{
    "name":"ram",
    "age":21,
    "mobile":"9494644363",
    "email":"ram@westagilelabs.com",
    "password":"ram123"
}

//new note
POST http://localhost:3002/notes
Content-Type: application/json

{
    "user_id":1,
    "note":"Today i am doing backend"
}
